### ISSUE TITLE
Missing Links to pre-trained checkpoints in the RUBER Readme.md

### ISSUE THREAD

**Issue by vgtomahawk** [iitmnlp/Dialogue-Evaluation-with-BERT#2]
Thanks for releasing the code, and especially along with baseline implementations!

The **Pre-trained Models** portion of the RUBER Readme [here](https://github.com/iitmnlp/Dialogue-Evaluation-with-BERT/tree/master/baselines/RUBER#pre-trained-models) appears to be phrased to refer to the pre-trained RUBER model checkpoints, as stated in the table enclosed - however the "here"s in the columns don't seem to point to any link.

Are these models downloadable or accessible from anywhere?

**Comment by akashkm99** [comment]
Hi, 

Thanks for pointing out the missing links. The readme has now been updated with the links to the checkpoints.

**Comment by hppy139** [comment]
missed again...
